# Generated by Django 3.1.3 on 2021-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved')], default='notrenew', max_length=15),
        ),
    ]
