# Generated by Django 3.1.3 on 2021-04-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20210424_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
