# Generated by Django 3.1.3 on 2021-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
