# Generated by Django 3.1.3 on 2021-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20210424_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='phone',
            field=models.IntegerField(default=777777777),
            preserve_default=False,
        ),
    ]
