# Generated by Django 3.1.3 on 2021-04-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_insurance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
