# Generated by Django 3.1.3 on 2021-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20210425_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('renewed', 'renewed')], default='requested', max_length=15),
        ),
    ]
