# Generated by Django 3.1.3 on 2021-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_auto_20210425_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyname',
        ),
        migrations.AddField(
            model_name='insurance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiclefotos/'),
        ),
    ]
