# Generated by Django 3.1.3 on 2021-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_auto_20210425_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'others')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
