# Generated by Django 3.1.3 on 2021-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='renew',
            field=models.CharField(choices=[('renew', 'renew'), ('notrenew', 'notrenew')], default='notrenew', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved')], default='disapproved', max_length=15),
        ),
    ]
