# Generated by Django 3.1.3 on 2021-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20210425_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
