# Generated by Django 3.1.3 on 2021-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_auto_20210427_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
