# Generated by Django 3.1.3 on 2021-06-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_auto_20210616_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='house_name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='insurance',
            name='cc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='coverage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('others', 'others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'car'), ('bike', 'bike'), ('commercial vehicles', 'commercial vehicles')], max_length=50, null=True),
        ),
    ]
